<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXXlZqda\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXXlZqda/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXXlZqda.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXXlZqda\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXXlZqda\App_KernelDevDebugContainer([
    'container.build_hash' => 'XXlZqda',
    'container.build_id' => 'bc5abd4a',
    'container.build_time' => 1714600287,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXXlZqda');
