version: '3.8'

services:
  php-fpm:
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
    restart: always
    container_name: php-fpm
    depends_on:
      - mysql
    networks:
      - myProject
    volumes:
      - ./../:/var/www/

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./../:/var/www/
    container_name: nginx
    restart: always
    ports:
      - "8001:81"
    networks:
      myProject: {}
    depends_on:
      - php-fpm

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_ROOT_PASSWORD=sofiya0505"
      - "MYSQL_DATABASE=symfony1"
    ports:
      - "3336:3306"
    networks:
      - myProject

networks:
  myProject:
    driver: bridge