version: '5'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./www:/www
    container_name: nginx
    restart: always
    ports:
      - "8001:81"
    networks:
      myProject: {}

  php-fpm:
    build:
      context: ./php-fpm
    restart: always
    container_name: php-fpm
    depends_on:
      - mysql
    networks:
      - myProject

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_ROOT_PASSWORD=sofiya0505"
      - "MYSQL_DATABASE=symfony1"
    ports:
      - "3336:3306"
    networks:
      - myProject

networks:
  myProject:
    driver: bridge